Node('root')
├── Node(u'root/Conglomerates')
│   └── Node(u'root/Conglomerates/Conglomerates')
│       └── Node(u'root/Conglomerates/Conglomerates/Conglomerates')
├── Node(u'root/Utilities')
│   ├── Node(u'root/Utilities/Utilities')
│   │   ├── Node(u'root/Utilities/Utilities/Electricity')
│   │   ├── Node(u'root/Utilities/Utilities/Gas Distribution')
│   │   ├── Node(u'root/Utilities/Utilities/Alternative/ Renewable Energy')
│   │   └── Node(u'root/Utilities/Utilities/Water')
│   └── Node(u'root/Utilities/Utilities(HSIC*)')
│       └── Node(u'root/Utilities/Utilities(HSIC*)/None')
├── Node(u'root/Properties & Construction')
│   ├── Node(u'root/Properties & Construction/Properties')
│   │   ├── Node(u'root/Properties & Construction/Properties/Property Investment')
│   │   ├── Node(u'root/Properties & Construction/Properties/Property Development')
│   │   └── Node(u'root/Properties & Construction/Properties/Real Estate Agencies')
│   └── Node(u'root/Properties & Construction/Construction')
│       ├── Node(u'root/Properties & Construction/Construction/Building Construction')
│       ├── Node(u'root/Properties & Construction/Construction/Construction Materials')
│       └── Node(u'root/Properties & Construction/Construction/Heavy Construction & Engineering')
├── Node(u'root/Financials')
│   ├── Node(u'root/Financials/Banks')
│   │   └── Node(u'root/Financials/Banks/Banks')
│   ├── Node(u'root/Financials/Other Financials')
│   │   ├── Node(u'root/Financials/Other Financials/Investment & Asset Management')
│   │   ├── Node(u'root/Financials/Other Financials/Financing')
│   │   ├── Node(u'root/Financials/Other Financials/Securities & Brokerage')
│   │   └── Node(u'root/Financials/Other Financials/Other Financials')
│   └── Node(u'root/Financials/Insurance')
│       └── Node(u'root/Financials/Insurance/Insurance')
├── Node(u'root/Materials')
│   ├── Node(u'root/Materials/Diversified Metals & Minerals')
│   │   ├── Node(u'root/Materials/Diversified Metals & Minerals/Other Metals & Minerals')
│   │   ├── Node(u'root/Materials/Diversified Metals & Minerals/Iron & Steel')
│   │   ├── Node(u'root/Materials/Diversified Metals & Minerals/Aluminium')
│   │   └── Node(u'root/Materials/Diversified Metals & Minerals/Copper')
│   ├── Node(u'root/Materials/Basic Materials')
│   │   ├── Node(u'root/Materials/Basic Materials/Specialty Chemicals')
│   │   ├── Node(u'root/Materials/Basic Materials/Forestry & Timber')
│   │   ├── Node(u'root/Materials/Basic Materials/Fertilisers & Agricultural Chemicals')
│   │   └── Node(u'root/Materials/Basic Materials/Paper')
│   └── Node(u'root/Materials/Gold & Precious Metals')
│       └── Node(u'root/Materials/Gold & Precious Metals/Gold & Precious Metals')
├── Node(u'root/Telecommunications')
│   ├── Node(u'root/Telecommunications/Telecommunications')
│   │   ├── Node(u'root/Telecommunications/Telecommunications/Telecommunication Services')
│   │   └── Node(u'root/Telecommunications/Telecommunications/Satellite & Wireless Communication')
│   └── Node(u'root/Telecommunications/Telecommunications(HSIC*)')
│       └── Node(u'root/Telecommunications/Telecommunications(HSIC*)/None')
├── Node(u'root/Consumer Services')
│   ├── Node(u'root/Consumer Services/Media & Entertainment')
│   │   ├── Node(u'root/Consumer Services/Media & Entertainment/Publishing')
│   │   ├── Node(u'root/Consumer Services/Media & Entertainment/Broadcasting')
│   │   ├── Node(u'root/Consumer Services/Media & Entertainment/Advertising & Marketing')
│   │   └── Node(u'root/Consumer Services/Media & Entertainment/Movies & Entertainment')
│   ├── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities')
│   │   ├── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities/Hotels & Resorts')
│   │   ├── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities/Casinos & Gaming')
│   │   ├── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities/Restaurants')
│   │   ├── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities/Travel & Tourism')
│   │   └── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities/Leisure & Recreational Facilities')
│   ├── Node(u'root/Consumer Services/Retailers')
│   │   ├── Node(u'root/Consumer Services/Retailers/Supermarkets & Convenience Stores')
│   │   └── Node(u'root/Consumer Services/Retailers/Department Stores')
│   ├── Node(u'root/Consumer Services/Transportation')
│   │   ├── Node(u'root/Consumer Services/Transportation/Airlines')
│   │   └── Node(u'root/Consumer Services/Transportation/Public Transport')
│   ├── Node(u'root/Consumer Services/Support Services')
│   │   └── Node(u'root/Consumer Services/Support Services/Support Services')
│   ├── Node(u'root/Consumer Services/Healthcare Services')
│   │   └── Node(u'root/Consumer Services/Healthcare Services/Medical & Aesthetic Services')
│   └── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities(HSIC*)')
│       └── Node(u'root/Consumer Services/Hotels, Casinos, Restaurants & Leisure Facilities(HSIC*)/None')
├── Node(u'root/Industrials')
│   ├── Node(u'root/Industrials/Industrial Engineering')
│   │   ├── Node(u'root/Industrials/Industrial Engineering/Industrial Components & Equipment')
│   │   ├── Node(u'root/Industrials/Industrial Engineering/Heavy Industrial Machinery')
│   │   ├── Node(u'root/Industrials/Industrial Engineering/Commercial Vehicles & Trucks')
│   │   ├── Node(u'root/Industrials/Industrial Engineering/New Energy Materials')
│   │   ├── Node(u'root/Industrials/Industrial Engineering/Environmental Engineering')
│   │   └── Node(u'root/Industrials/Industrial Engineering/Aerospace & Defence')
│   ├── Node(u'root/Industrials/Industrial Transportation')
│   │   ├── Node(u'root/Industrials/Industrial Transportation/Railway & Tollroad Operation')
│   │   ├── Node(u'root/Industrials/Industrial Transportation/Shipping & Port Operation')
│   │   └── Node(u'root/Industrials/Industrial Transportation/Air Freight & Logistics')
│   └── Node(u'root/Industrials/Commercial & Professional Services')
│       ├── Node(u'root/Industrials/Commercial & Professional Services/Printing & Packaging')
│       └── Node(u'root/Industrials/Commercial & Professional Services/Sourcing & Supply Chain Service')
├── Node(u'root/Consumer Goods')
│   ├── Node(u'root/Consumer Goods/Household Goods & Electronics')
│   │   ├── Node(u'root/Consumer Goods/Household Goods & Electronics/Toys & Leisure Products')
│   │   ├── Node(u'root/Consumer Goods/Household Goods & Electronics/Consumer Electronics')
│   │   ├── Node(u'root/Consumer Goods/Household Goods & Electronics/Home Appliances')
│   │   └── Node(u'root/Consumer Goods/Household Goods & Electronics/Household Goods')
│   ├── Node(u'root/Consumer Goods/Textiles, Clothing & Personal Care')
│   │   ├── Node(u'root/Consumer Goods/Textiles, Clothing & Personal Care/Apparel')
│   │   ├── Node(u'root/Consumer Goods/Textiles, Clothing & Personal Care/Textiles & Fabrics')
│   │   ├── Node(u'root/Consumer Goods/Textiles, Clothing & Personal Care/Jewellery & Timepieces')
│   │   ├── Node(u'root/Consumer Goods/Textiles, Clothing & Personal Care/Other Accessories')
│   │   ├── Node(u'root/Consumer Goods/Textiles, Clothing & Personal Care/Cosmetics & Personal Care')
│   │   └── Node(u'root/Consumer Goods/Textiles, Clothing & Personal Care/Footwear')
│   ├── Node(u'root/Consumer Goods/Agricultural Products')
│   │   ├── Node(u'root/Consumer Goods/Agricultural Products/Animal Feeds')
│   │   ├── Node(u'root/Consumer Goods/Agricultural Products/Agricultural Products')
│   │   └── Node(u'root/Consumer Goods/Agricultural Products/Poultry & Meat')
│   ├── Node(u'root/Consumer Goods/Food & Beverages')
│   │   ├── Node(u'root/Consumer Goods/Food & Beverages/Packaged Foods')
│   │   ├── Node(u'root/Consumer Goods/Food & Beverages/Alcohols')
│   │   ├── Node(u'root/Consumer Goods/Food & Beverages/None')
│   │   ├── Node(u'root/Consumer Goods/Food & Beverages/Food Additives')
│   │   └── Node(u'root/Consumer Goods/Food & Beverages/Dairy Products')
│   ├── Node(u'root/Consumer Goods/Automobiles')
│   │   ├── Node(u'root/Consumer Goods/Automobiles/Automobiles')
│   │   └── Node(u'root/Consumer Goods/Automobiles/Auto Parts')
│   └── Node(u'root/Consumer Goods/Healthcare')
│       ├── Node(u'root/Consumer Goods/Healthcare/Pharmaceuticals')
│       ├── Node(u'root/Consumer Goods/Healthcare/Medical Devices')
│       └── Node(u'root/Consumer Goods/Healthcare/Biotechnology')
├── Node(u'root/Information Technology')
│   ├── Node(u'root/Information Technology/Software & Services')
│   │   ├── Node(u'root/Information Technology/Software & Services/System Applications & IT Consulting')
│   │   ├── Node(u'root/Information Technology/Software & Services/None')
│   │   └── Node(u'root/Information Technology/Software & Services/Software')
│   ├── Node(u'root/Information Technology/Semiconductors')
│   │   └── Node(u'root/Information Technology/Semiconductors/Semiconductors')
│   └── Node(u'root/Information Technology/IT Hardware')
│       ├── Node(u'root/Information Technology/IT Hardware/Telecommunication Equipment')
│       └── Node(u'root/Information Technology/IT Hardware/Computers & Peripherals')
└── Node(u'root/Energy')
    ├── Node(u'root/Energy/Coal')
    │   └── Node(u'root/Energy/Coal/Coal')
    └── Node(u'root/Energy/Oil & Gas')
        ├── Node(u'root/Energy/Oil & Gas/Oil & Gas Producers')
        └── Node(u'root/Energy/Oil & Gas/Oil & Gas Equipment & Services')
